Application
L4pki/Recipes pull request #2
Opened 2024-10-28 05:19 UTC by L4pki

2024-10-28 15:34 UTC, AlekseiPavlovskii requested changes

2024-10-28 15:34 UTC, AlekseiPavlovskii commented on Application/Sequrity/IPasswordHaser.cs
> +public interface IPasswordHasher
Нет пробела

2024-10-28 15:34 UTC, AlekseiPavlovskii commented on Application/Sequrity/PasswordHasher.cs
> +public class PasswordHasher : IPasswordHasher
Нет пробела

2024-10-28 15:34 UTC, AlekseiPavlovskii commented on Application/Sequrity/PasswordHasher.cs
> +namespace Application.Sequrity;
Ошибка в именовании

2024-10-28 15:34 UTC, AlekseiPavlovskii commented on Application/Sequrity/PasswordHasher.cs
> +    public bool VerifyPassword( string hashedPassword, string password )
Правильнее оставить тут только хеширование, а верифицировать на уровень выше

2024-10-28 15:34 UTC, AlekseiPavlovskii commented on Application/Sequrity/PasswordHasher.cs
> +        if ( passwordHash == hashedPassword )
If не нужен

2024-10-28 15:34 UTC, AlekseiPavlovskii commented on Application/Services/UserLoginService.cs
> +namespace Application.Services;
Нет пробела

2024-10-28 15:34 UTC, AlekseiPavlovskii commented on Application/Services/UserLoginService.cs
> +        if ( string.IsNullOrWhiteSpace( login ) || string.IsNullOrWhiteSpace( password ) )
Логику валидации лучше вынести в отдельный метод

2024-10-28 15:34 UTC, AlekseiPavlovskii commented on Application/Services/UserRegistrationService.cs
> +        if ( string.IsNullOrWhiteSpace( login ) || string.IsNullOrWhiteSpace( password ) || string.IsNullOrWhiteSpace( name ) )
Логику валидации лучше вынести в отдельный метод

2024-10-28 15:34 UTC, AlekseiPavlovskii commented on Application/Services/UserRegistrationService.cs
> +    public UserRegistrationService( IUserRepository userRepository, IPasswordHasher passwordHasher )
Лучше оставить UserService, и в нем хранить и логику регистрации, и логику авторизации

2024-10-28 15:34 UTC, AlekseiPavlovskii commented on Domain/Entities/RecipeEntities/Step.cs
> +public class Step
Нет пробела

2024-10-28 15:34 UTC, AlekseiPavlovskii commented on Domain/Entities/RecipeEntities/Tag.cs
> +public class Tag
Нет пробела

2024-10-28 15:34 UTC, AlekseiPavlovskii commented on Domain/Interfaces/IRecipeRepository.cs
> +public interface IRecipeRepository
Нет пробела

2024-10-28 15:34 UTC, AlekseiPavlovskii commented on Domain/Interfaces/IUserRepository.cs
> +namespace Domain.Interfaces;
Нет пробела

2024-10-28 15:34 UTC, AlekseiPavlovskii commented on Infrastructure/Data/Configuration/IngridientConfiguration.cs
> +public class IngridientConfiguration : IEntityTypeConfiguration<Ingridient>
Нет пробела

2024-10-28 15:34 UTC, AlekseiPavlovskii commented on Infrastructure/Data/Configuration/RecipeConfiguration.cs
> +public class RecipeConfiguration : IEntityTypeConfiguration<Recipe>
Нет пробела

2024-10-28 15:34 UTC, AlekseiPavlovskii commented on Infrastructure/Data/Configuration/TagConfiguration.cs
> +public class TagConfiguration : IEntityTypeConfiguration<Tag>
Нет пробела

2024-10-28 15:34 UTC, AlekseiPavlovskii commented on Infrastructure/Data/Configuration/UserConfiguration.cs
> +public class UserConfiguration : IEntityTypeConfiguration<User>
Нет пробела

2024-10-28 15:34 UTC, AlekseiPavlovskii commented on Infrastructure/Data/RecipeDbContext.cs
> +public class RecipeDbContext : DbContext
Нет пробела

2024-10-28 15:34 UTC, AlekseiPavlovskii commented on Infrastructure/Repositories/RecipeRepository.cs
> +public class RecipeRepository : IRecipeRepository
Нет пробела

2024-10-28 15:34 UTC, AlekseiPavlovskii commented on Infrastructure/Repositories/UserRepository.cs
> +public class UserRepository : IUserRepository
Нет пробела

2024-10-28 15:34 UTC, AlekseiPavlovskii commented on Infrastructure/Repositories/RecipeRepository.cs
> +        var recipe = _recipeDbContext.Set<Recipe>().FirstOrDefault( r => r.Id == id );
var

2024-10-28 15:34 UTC, AlekseiPavlovskii commented on Infrastructure/Repositories/RecipeRepository.cs
> +        var recipe = _recipeDbContext.Set<Recipe>().FirstOrDefault( r => r.Id == modifiedRecipe.Id );
var

2024-10-28 15:34 UTC, AlekseiPavlovskii commented on Infrastructure/Repositories/RecipeRepository.cs
> +        var topLikedRecipes = mostLikedRecipes
var

2024-10-28 15:34 UTC, AlekseiPavlovskii commented on Infrastructure/Repositories/UserRepository.cs
> +        if ( GetUserByLogin( login ) == null )
if не нужен

2024-10-28 15:34 UTC, AlekseiPavlovskii commented on Infrastructure/Repositories/UserRepository.cs
> +        var user = _recipeDbContext.Set<User>().FirstOrDefault( u => u.Login == login );
var

2024-10-28 15:34 UTC, AlekseiPavlovskii commented on Infrastructure/Repositories/UserRepository.cs
> +        if ( user == null )
if не нужен

2024-10-28 15:34 UTC, AlekseiPavlovskii commented on Infrastructure/Repositories/UserRepository.cs
> +        var user = _recipeDbContext.Set<User>().FirstOrDefault( u => u.Id == id );
var

2024-11-05 02:14 UTC, L4pki commented on Application/Sequrity/PasswordHasher.cs
> +        if ( passwordHash == hashedPassword )
Удалил верификацию, вынес на уровень выше

2024-11-05 02:15 UTC, L4pki commented on Application/Services/UserLoginService.cs
> +namespace Application.Services;
Удалил сервисы все реализуется через MediatR

2024-11-20 13:37 UTC, merged